language: php

branches:
  only:
    - master

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - DEFAULT=1 DATABASE_TEST_URL='mysql://ishan:vyas@127.0.0.1/test_cakevue_spa'

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0
    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0

before_install:
  - phpenv config-rm xdebug.ini

install:
  - mysql -u root -e "CREATE DATABASE test_cakevue_spa; CREATE USER 'ishan'@'localhost' IDENTIFIED BY 'vyas'; GRANT ALL ON test_cakevue_spa.* TO 'ishan'@'localhost';"
  - composer install --no-interaction

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer analyse; fi

notifications:
  email: false
